<?php
namespace App\Libraries;
use App\Models\SettingModel;
class ReportLib {
    public function __construct(private MailLib $mail) {}
    private function db() { return \Config\Database::connect(); }
    public function stats(string $s, string $e): array {
        $d = $this->db();
        $c = fn(string $table, ?string $extra = null, string $col = 'created_at') => (int) $d->table($table)
            ->where("$col >=", $s)->where("$col <=", $e)
            ->when($extra !== null, fn($q) => $q->where($extra))->countAllResults(false);
        return [
            'tickets' => $c('tickets'),
            'tasks' => $c('tasks'),
            'tasks_completed' => $c('tasks', ['status' => 'completed']),
            'tasks_pending' => (int) $d->table('tasks')->where('created_at >=', $s)->where('created_at <=', $e)->whereIn('status', ['new','in_progress','waiting_parts'])->countAllResults(false),
            'awaiting_approval' => $c('tasks', ['status' => 'waiting_approval']),
            'signatures' => $c('signatures', null, 'signed_at'),
            'project_cost' => (float) ($d->table('tasks')->select('COALESCE(SUM(parts_cost+labor_cost),0) AS c')->where('created_at >=', $s)->where('created_at <=', $e)->where('scope', 'project')->get()->getRow()->c ?? 0),
        ];
    }
    public function work(string $s, string $e): array {
        return $this->db()->table('tasks')
            ->select('tasks.*, tickets.ticket_number, clients.name AS client_name')
            ->join('tickets', 'tickets.id = tasks.ticket_id')
            ->join('clients', 'clients.id = tickets.client_id')
            ->where('tasks.created_at >=', $s)->where('tasks.created_at <=', $e)
            ->orderBy('tasks.id')->get()->getResultArray();
    }
    public function html(string $title, array $stats, array $work): string {
        $cell = 'style="border:1px solid #ddd;padding:6px;"';
        $rows = '';
        foreach ($work as $w) {
            $rows .= '<tr><td '.$cell.'>'.esc($w['ticket_number']).'</td><td '.$cell.'>'.esc($w['client_name']).'</td><td '.$cell.'>'.esc($w['item']).'</td><td '.$cell.'>'.nl2br(esc($w['action_taken'])).'</td><td '.$cell.'>'.esc($w['status']).'</td><td '.$cell.'>'.esc(ucfirst($w['scope'])).'</td><td '.$cell.' style="text-align:right;">'.number_format((float)$w['parts_cost']+(float)$w['labor_cost'],2).'</td></tr>';
        }
        if ($rows === '') $rows = '<tr><td colspan="7" '.$cell.'>No work logged.</td></tr>';
        return '<html><body style="font-family:Arial;padding:20px;background:#f4f4f4;"><div style="max-width:900px;margin:0 auto;background:#fff;padding:30px;border-radius:8px;">'
            .'<h2 style="color:#0f172a;">'.$title.'</h2><h3>Executive Summary</h3><table style="width:100%;border-collapse:collapse;">'
            .'<tr><td '.$cell.'>Tickets</td><td '.$cell.'>'.$stats['tickets'].'</td></tr>'
            .'<tr><td '.$cell.'>Tasks</td><td '.$cell.'>'.$stats['tasks'].'</td></tr>'
            .'<tr><td '.$cell.'>Completed</td><td '.$cell.'>'.$stats['tasks_completed'].'</td></tr>'
            .'<tr><td '.$cell.'>Pending</td><td '.$cell.'>'.$stats['tasks_pending'].'</td></tr>'
            .'<tr><td '.$cell.'>Awaiting approval</td><td '.$cell.'>'.$stats['awaiting_approval'].'</td></tr>'
            .'<tr><td '.$cell.'>Sign-offs</td><td '.$cell.'>'.$stats['signatures'].'</td></tr>'
            .'<tr><td '.$cell.'>Project cost</td><td '.$cell.' style="text-align:right;">'.number_format($stats['project_cost'],2).'</td></tr></table>'
            .'<h3>Work Log</h3><table style="width:100%;border-collapse:collapse;font-size:13px;"><tr style="background:#f8fafc;"><th '.$cell.'>Ticket</th><th '.$cell.'>Client</th><th '.$cell.'>Item</th><th '.$cell.'>Action</th><th '.$cell.'>Status</th><th '.$cell.'>Scope</th><th '.$cell.'>Cost</th></tr>'.$rows.'</table>'
            .'<p style="font-size:12px;color:#64748b;">Full financials from Accounts. Auto-generated by IT Support System (CodeIgniter 4).</p></div></body></html>';
    }
    public function sendMonthly(string $ym): bool {
        $start = $ym.'-01'; $end = date('Y-m-t', strtotime($start)).' 23:59:59';
        $label = date('F Y', strtotime($start));
        $ok = $this->mail->send($this->mail->recipients('monthly_report_recipients'), 'Monthly ICT Report - '.$label, $this->html('Monthly ICT Management Report - '.$label, $this->stats($start,$end), $this->work($start,$end)));
        if ($ok) SettingModel::set('monthly_report_last_sent', $ym);
        return $ok;
    }
    public function sendWeekly(string $ymd): bool {
        $start = date('Y-m-d', strtotime($ymd)); $end = date('Y-m-d', strtotime($ymd.' +6 days')).' 23:59:59';
        $label = 'Week of '.date('M j, Y', strtotime($start));
        $ok = $this->mail->send($this->mail->recipients('weekly_report_recipients'), 'Weekly ICT Report - '.$label, $this->html('Weekly ICT Report - '.$label, $this->stats($start,$end), $this->work($start,$end)));
        if ($ok) SettingModel::set('weekly_report_last_sent', $ymd);
        return $ok;
    }
}