<?= view('itsupport/_header') ?>
<section class="feature-intro">
    <p class="eyebrow">BUILT FOR EVERYDAY SUPPORT</p>
    <h2>Tools your team can use today</h2>
    <p class="muted">A clear overview of the modules available in this installation.</p>
</section>
<section class="grid grid-2 feature-grid" aria-label="Available system features">
    <article class="card feature-card"><span class="feature-icon">01</span><div><span class="badge green">Available</span><h3>Tickets &amp; field service</h3><p>Create support tickets, record technician tasks, track costs and visit dates, attach photos, and collect client sign-off.</p><a class="button secondary" href="<?= base_url('its-tickets') ?>">Open tickets</a></div></article>
    <article class="card feature-card"><span class="feature-icon">02</span><div><span class="badge green">Available</span><h3>Clients &amp; assets</h3><p>Keep client contact details, track linked equipment, log repairs, new builds and RAM/SSD upgrades per machine (specs update automatically), and use QR links for asset records.</p><div class="quick-actions"><a class="button secondary" href="<?= base_url('its-clients') ?>">Clients</a><a class="button secondary" href="<?= base_url('its-assets') ?>">Assets</a></div></div></article>
    <article class="card feature-card"><span class="feature-icon">03</span><div><span class="badge green">Available</span><h3>Network, cameras &amp; credential vault</h3><p>Register equipment, store encrypted credentials and admin-managed RTSP/RTSPS URLs, and monitor an admin-configured TCP port on demand or by the token-protected schedule. MikroTik supports TLS RouterOS reboot, Wi-Fi client, and DHCP lease actions; Hikvision NVRs support verified HTTPS ISAPI storage checks and reboot. Credentials and stream URLs are encrypted at rest.</p><a class="button secondary" href="<?= base_url('its-network') ?>">Open network register</a></div></article>
    <article class="card feature-card"><span class="feature-icon">04</span><div><span class="badge green">Available</span><h3>Custom forms &amp; reports</h3><p>Build forms with 11 field types including radio, URL, phone, and private file uploads. Review responses, or create saved module reports with date/status filters, grouping, sorting, CSV, JSON, and GZIP JSON exports.</p><div class="quick-actions"><a class="button secondary" href="<?= base_url('its-forms') ?>">Open forms</a><?php if ((session('its_user')['role'] ?? '') === 'admin') { ?><a class="button secondary" href="<?= base_url('its-report-builder') ?>">Report builder</a><?php } ?></div></div></article>
    <article class="card feature-card"><span class="feature-icon">05</span><div><span class="badge green">Available</span><h3>Quotes &amp; approvals</h3><p>Build quotes with itemized pricing, send approval links, and keep the approval status with the quote.</p><a class="button secondary" href="<?= base_url('its-quotes') ?>">Open quotes</a></div></article>
    <article class="card feature-card"><span class="feature-icon">06</span><div><span class="badge green">Available</span><h3>Dashboard &amp; statistics</h3><p>See client, asset, ticket, quote, and project totals with live ticket-volume, ticket-status, monthly cost, and network manufacturer charts.</p><a class="button secondary" href="<?= base_url('its-dashboard') ?>">View dashboard</a></div></article>
    <article class="card feature-card"><span class="feature-icon">07</span><div><span class="badge green">Available</span><h3>Templates &amp; appearance</h3><p>Admins can save reusable workflow templates, company branding, and a workspace color theme. Users can choose persistent dark mode, display language for shared navigation, and one of four text sizes.</p><a class="button secondary" href="<?= base_url('its-admin?tab=templates') ?>">Manage templates</a></div></article>
    <article class="card feature-card"><span class="feature-icon">08</span><div><span class="badge green">Available</span><h3>Live dashboard &amp; installable app</h3><p>Dashboard metrics refresh automatically. The app can be installed as a PWA and shows a privacy-safe offline page without caching private records.</p><a class="button secondary" href="<?= base_url('its-dashboard') ?>">Open dashboard</a></div></article>
    <article class="card feature-card"><span class="feature-icon">09</span><div><span class="badge green">Available</span><h3>Administration &amp; audit</h3><p>Manage users, company details, scheduled maintenance, mail settings, download compressed GZIP database backups, and view audit history.</p><?php if ((session('its_user')['role'] ?? '') === 'admin') { ?><a class="button secondary" href="<?= base_url('its-admin') ?>">Open administration</a><?php } ?></div></article>
    <article class="card feature-card"><span class="feature-icon">09</span><div><span class="badge green">Available</span><h3>Client portal &amp; ticket conversation</h3><p>Clients sign in to report issues, follow progress, reply, and see open and resolved counts. Staff can post public replies or internal notes that clients never see.</p><a class="button secondary" href="<?= base_url('its-tickets') ?>">Open tickets</a></div></article>
    <article class="card feature-card"><span class="feature-icon">10</span><div><span class="badge green">Available</span><h3>Ticket board</h3><p>Drag tickets between status columns, or use the status menu on each card.</p><a class="button secondary" href="<?= base_url('its-board') ?>">Open board</a></div></article>
    <article class="card feature-card"><span class="feature-icon">11</span><div><span class="badge green">Available</span><h3>System updates</h3><p>Version, server and framework details, update checks, ZIP package upload, integrity checks, backups with auto-heal, and an update log. Admin only.</p><a class="button secondary" href="<?= base_url('its-updates') ?>">Open updates</a></div></article>
    <article class="card feature-card"><span class="feature-icon">12</span><div><span class="badge green">Available</span><h3>Enterprise controls</h3><p>Two-factor login, lockout, role permissions, SLA tracking, time logging, ratings, knowledge base, Ctrl+K search, REST API, webhooks and a health page.</p><a class="button secondary" href="<?= base_url('its-security') ?>">Open security</a></div></article></section>
<section class="card planned-features">
    <p class="eyebrow">ROADMAP</p><h3>Not included in this build yet</h3>
    <p class="muted">These capabilities are described in the supplied feature specification but are not fully wired into this installation yet.</p>
    <div class="quick-actions"><span class="badge gray">Full translations across all modules</span><span class="badge gray">SNMP/SSH monitoring</span><span class="badge gray">Additional vendor-specific remote management</span><span class="badge gray">Hosted one-click update feed (needs your own manifest)</span></div>
</section>
<style>
.feature-intro{padding:8px 2px 20px}.feature-intro h2{margin:5px 0;font-size:28px}.feature-intro p{margin:0}.feature-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr))}.feature-card{display:grid;grid-template-columns:40px 1fr;gap:14px;margin:0;min-height:205px}.feature-card h3{margin:11px 0 7px}.feature-card p{margin:0 0 15px;color:#68788e;font-size:13px}.feature-icon{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--brand-soft);color:var(--brand-dark);font-size:12px;font-weight:800}.planned-features{margin-top:20px}.planned-features h3{margin:4px 0}.planned-features p{margin:7px 0 16px}
</style>
<?= view('itsupport/_footer') ?>
