<?= view('itsupport/_header') ?>
<section class="reports-intro">
    <p class="eyebrow">INSIGHTS, ON YOUR TERMS</p>
    <h2>Report builder</h2>
    <p class="muted">Choose a dataset, columns, date range, status, grouping and sort order, then export or save the setup.</p>
</section>
<?php foreach ($errors as $error) { ?><div class="flash flash-err" role="alert"><?= esc($error) ?></div><?php } ?>
<section class="grid grid-2 report-layout">
    <div class="card">
        <form method="get" action="<?= base_url('its-report-builder') ?>" id="report-config">
            <label for="report-module">Module</label>
            <select name="module" id="report-module" onchange="this.form.submit()"><?php foreach ($modules as $key => $module) { ?><option value="<?= esc($key) ?>" <?= $config['module'] === $key ? 'selected' : '' ?>><?= esc($module['label']) ?></option><?php } ?></select>
            <fieldset><legend>Columns (up to 12)</legend><div class="report-columns"><?php foreach ($modules[$config['module']]['fields'] as $key => [$expression, $label]) { ?><label class="report-column"><input type="checkbox" name="columns[]" value="<?= esc($key) ?>" <?= in_array($key, $config['columns'], true) ? 'checked' : '' ?>><?= esc($label) ?></label><?php } ?></div></fieldset>
            <div class="grid grid-2"><div><label for="report-from">From</label><input id="report-from" type="date" name="from" value="<?= esc($config['from']) ?>"></div><div><label for="report-to">To</label><input id="report-to" type="date" name="to" value="<?= esc($config['to']) ?>"></div></div>
            <?php if ($modules[$config['module']]['status']) { ?><label for="report-status">Status (optional)</label><select id="report-status" name="status"><option value="">Any status</option><?php foreach (['new','in_progress','waiting_parts','waiting_approval','completed','closed','draft','sent','approved','rejected','active','inactive','maintenance'] as $status) { ?><option value="<?= esc($status) ?>" <?= $config['status'] === $status ? 'selected' : '' ?>><?= esc(ucwords(str_replace('_', ' ', $status))) ?></option><?php } ?></select><?php } ?>
            <div class="grid grid-2"><div><label for="report-group">Group by</label><select id="report-group" name="group"><option value="">No grouping</option><?php foreach ($modules[$config['module']]['fields'] as $key => [$expression, $label]) { ?><option value="<?= esc($key) ?>" <?= $config['group'] === $key ? 'selected' : '' ?>><?= esc($label) ?></option><?php } ?></select></div><div><label for="report-sort">Sort by</label><select id="report-sort" name="sort"><option value="">Date created</option><?php foreach ($modules[$config['module']]['fields'] as $key => [$expression, $label]) { ?><option value="<?= esc($key) ?>" <?= $config['sort'] === $key ? 'selected' : '' ?>><?= esc($label) ?></option><?php } ?></select></div></div>
            <label for="report-direction">Sort order</label><select id="report-direction" name="direction"><option value="desc" <?= $config['direction'] === 'desc' ? 'selected' : '' ?>>Descending</option><option value="asc" <?= $config['direction'] === 'asc' ? 'selected' : '' ?>>Ascending</option></select>
            <div class="quick-actions"><button class="btn">Run report</button><?php foreach (['csv'=>'CSV','json'=>'JSON','gzip'=>'GZIP JSON'] as $format => $label) { ?><button class="button secondary" name="export" value="<?= esc($format) ?>"><?= esc($label) ?></button><?php } ?></div>
        </form>
        <form method="post" action="<?= base_url('its-report-builder-save') ?>" class="save-report"><?= csrf_field() ?>
            <input type="hidden" name="module" value="<?= esc($config['module']) ?>"><?php foreach ($config['columns'] as $column) { ?><input type="hidden" name="columns[]" value="<?= esc($column) ?>"><?php } ?>
            <input type="hidden" name="from" value="<?= esc($config['from']) ?>"><input type="hidden" name="to" value="<?= esc($config['to']) ?>"><input type="hidden" name="status" value="<?= esc($config['status']) ?>"><input type="hidden" name="group" value="<?= esc($config['group']) ?>"><input type="hidden" name="sort" value="<?= esc($config['sort']) ?>"><input type="hidden" name="direction" value="<?= esc($config['direction']) ?>">
            <label for="report-name">Save this setup</label><div class="save-line"><input id="report-name" name="name" maxlength="100" placeholder="e.g. Open tickets by client" required><button class="btn secondary">Save template</button></div>
        </form>
    </div>
    <aside class="card saved-reports"><h3>Saved templates</h3><?php if ($savedReports) { ?><ul><?php foreach ($savedReports as $report) { ?><li><a href="<?= base_url('its-report-builder-load/' . rawurlencode($report['id'])) ?>"><?= esc($report['name']) ?></a><form method="post" action="<?= base_url('its-report-builder-delete/' . rawurlencode($report['id'])) ?>" onsubmit="return confirm('Delete this report template?')"><?= csrf_field() ?><button class="btn danger" aria-label="Delete <?= esc($report['name']) ?>">Delete</button></form></li><?php } ?></ul><?php } else { ?><p class="muted">Save a report setup for one-click reuse.</p><?php } ?></aside>
</section>
<section class="card"><div class="section-heading"><h3>Results</h3><span class="badge gray"><?= count($rows) ?> rows<?= count($rows) === 5000 ? ' · 5,000 row limit reached' : '' ?></span></div>
<?php if ($rows) { ?><div class="tbl"><table><thead><tr><?php foreach (array_keys($rows[0]) as $key) { ?><th><?= esc($config['group'] !== '' ? ($key === 'group_value' ? $modules[$config['module']]['fields'][$config['group']][1] : 'Records') : ($modules[$config['module']]['fields'][$key][1] ?? $key)) ?></th><?php } ?></tr></thead><tbody><?php foreach ($rows as $row) { ?><tr><?php foreach ($row as $value) { ?><td><?= esc(is_scalar($value) ? (string) $value : '') ?></td><?php } ?></tr><?php } ?></tbody></table></div><?php } else { ?><p class="muted">Run a report to see results here.</p><?php } ?>
</section>
<style>
.reports-intro{padding:8px 2px 14px}.reports-intro h2{margin:4px 0;font-size:30px}.reports-intro p{margin:0}.report-layout{grid-template-columns:minmax(0,2fr) minmax(240px,1fr)}.report-layout fieldset{border:1px solid var(--line);border-radius:14px;padding:14px;margin:0 0 14px}.report-columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:6px}.report-column{display:flex;align-items:center;gap:8px;padding:8px;border-radius:9px;background:var(--canvas)}.report-column input{width:16px;margin:0}.save-report{border-top:1px solid var(--line);margin-top:18px;padding-top:14px}.save-line{display:flex;gap:8px}.save-line input{margin:5px 0}.saved-reports ul{padding:0;list-style:none}.saved-reports li{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.saved-reports li:last-child{border:0}.saved-reports li form{margin:0}.saved-reports .btn{padding:6px 9px;font-size:11px}@media(max-width:760px){.report-layout{grid-template-columns:1fr}.save-line{flex-direction:column}}
</style>
<?= view('itsupport/_footer') ?>
